// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjip9U1t3Xs6H4j3o1lcK4tgTLikflgnU',
    appId: '1:949219386468:web:a952f1e76993477e712b71',
    messagingSenderId: '949219386468',
    projectId: 'sanjayamarket-b5c81',
    authDomain: 'sanjayamarket-b5c81.firebaseapp.com',
    storageBucket: 'sanjayamarket-b5c81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApSD3qBpdqy0rZSWF5KgXVA3-vIY8_8Aw',
    appId: '1:949219386468:android:0ab89e93d4b2351b712b71',
    messagingSenderId: '949219386468',
    projectId: 'sanjayamarket-b5c81',
    storageBucket: 'sanjayamarket-b5c81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0SFrZYVsLbtls-V0opYQNqbgR9NCwzOs',
    appId: '1:949219386468:ios:6cf2d6ac9cb5eb6e712b71',
    messagingSenderId: '949219386468',
    projectId: 'sanjayamarket-b5c81',
    storageBucket: 'sanjayamarket-b5c81.appspot.com',
    iosClientId: '949219386468-b6qip2jv559v6s2pr33quu006ed6u42i.apps.googleusercontent.com',
    iosBundleId: 'com.akbar76.sanjay.sanjaya',
  );
}
